spring:
  application:
    name: CodeIntegration
  profiles:
    active: druid
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
server:
  port: 8080

mybatis-plus:
  type-aliases-package: cn.machaojin.mapper
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sonar:
  baseUrl: http://localhost:9000
  token: squ_0d47db2d394dad0d52bc10f2da3d4b70f9345c4a
  basePackage: D:\\GitProject
  username: Ma Chaojin
  password: 123456