spring:
  application:
    name: CodeIntegration
  profiles:
    active: druid
server:
  port: 8080

mybatis-plus:
  type-aliases-package: cn.machaojin.mapper
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sonar:
  baseUrl: http://localhost:9000
  token: squ_0d47db2d394dad0d52bc10f2da3d4b70f9345c4a